### ISSUE TITLE
Unable to find uploaded artifact - [ Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct. ]

### ISSUE THREAD

**Issue by punit1108** [actions/deploy-pages#102]
I tried deploying to my GH Pages after a couple of months and i am unable to do it.

The following is the error I am getting - 

![image](https://user-images.githubusercontent.com/7887355/216236470-107c6055-4552-49f5-a0e4-d80e965c0522.png)

My workflow file currently looks like so - 

```yaml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  deployments: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
#     - run: npm test
    - uses: actions/upload-artifact@master
      with:
        name: 'artifact'
        path: './build' 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - uses: actions/download-artifact@master
      with:
        name: 'artifact'
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: 'artifact'
        path: '/home/runner/work/punit1108.github.io/punit1108.github.io'
    - run: ls /home/runner/work/punit1108.github.io/punit1108.github.io
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
```
