### ISSUE TITLE
Failure without error code

### ISSUE THREAD

**Issue by Anna-Dan** [actions/deploy-pages#13]
I'm trying to deploy my built page to pages, but this action seems to fail without any error code, just "Try again later".
Config:
```
name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist
          if-no-files-found: warn
  deploy-to-pages:
    runs-on: ubuntu-latest
    name: Deploy to Pages
    needs: build
    permissions:
      id-token: write
      contents: read
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1-beta
```
The result:

> Actor: Anna-Dan
> Action ID: 1756432244
> Artifact URL: https://pipelines.actions.githubusercontent.com/5hihSr89L1pjn3eRto3775mYg7aBQ4fzNhi7FrUXnmaqcyGjxl/_apis/pipelines/workflows/1756432244/artifacts?api-version=6.0-preview
> {"count":1,"value":[{"containerId":11236909,"size":818739,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/5hihSr89L1pjn3eRto3775mYg7aBQ4fzNhi7FrUXnmaqcyGjxl/_apis/resources/Containers/11236909","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/5hihSr89L1pjn3eRto3775mYg7aBQ4fzNhi7FrUXnmaqcyGjxl/_apis/pipelines/1/runs/23/artifacts?artifactName=github-pages","expiresOn":"2022-04-27T15:53:58.0671261Z","items":null}]}
> Creating deployment with payload:
> {
> 	"artifact_url": "https://pipelines.actions.githubusercontent.com/5hihSr89L1pjn3eRto3775mYg7aBQ4fzNhi7FrUXnmaqcyGjxl/_apis/pipelines/1/runs/23/artifacts?artifactName=github-pages&%24expand=SignedContent",
> 	"pages_build_version": "de8e11ae6f4ebfee2c48f33c613aee996d97aea1",
> 	"oidc_token": "***"
> }
> Created deployment for de8e11ae6f4ebfee2c48f33c613aee996d97aea1
> {"page_url":"https://anna-dan.github.io/mesto/","status_url":"https://api.github.com/repos/Anna-Dan/mesto/pages/deployment/status/de8e11ae6f4ebfee2c48f33c613aee996d97aea1"}
> 
> Current status: deployment_queued
> Error: Deployment failed, try again later.
> Sending telemetry for run id 1756432244
