### ISSUE TITLE
Tags unable to deploy to pages

### ISSUE THREAD

**Issue by akshaybabloo** [actions/deploy-pages#151]
I am trying to deploy to pages when the software is released. But I keep getting error saying that `Branch "v1.1.2" is not allowed to deploy to github-pages due to environment protection rules.`

The actions file look like:

```yaml
name: Deploy Sphinx Docs to GitHub Pages

on:
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Build
        run: |
          cd _docs
          pipenv run make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _docs/_build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

it works fine on `main` branch
