### ISSUE TITLE
Empty output.page_url despite successful deployment

### ISSUE THREAD

**Issue by elasticdog** [actions/deploy-pages#161]
I have a job defined to deploy my project documentation to the github-pages environment, but despite the deployment working as expected, there's a warning annotation on the workflow that states:

> Environment URL '' is not a valid http(s) URL, so it will not be shown as a link in the workflow graph.

I've tried setting the [default access permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) for the `GITHUB_TOKEN` to both my repository's default "restricted", as well as the "permissive" settings, but it has not made a difference.

If it's helpful, I'd be glad to paste any of the job output from a run here, but for reference, this is [my job definition](https://github.com/elasticdog/rustops-blueprint/blob/56774fa7e8ea10b8eb13d190871dacfb5ea67083/.github/workflows/docs.yml):

```yaml
  deploy:
    name: deploy / github-pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

Relates to https://github.com/elasticdog/rustops-blueprint/pull/18
