### ISSUE TITLE
actions/deploy-pages v2 failing with HttpError: Invalid artifact url

### ISSUE THREAD

**Issue by matthewfeickert** [actions/deploy-pages#225]
Hi. I have a GitHub Pages deployement workflow (at https://github.com/matthewfeickert/chep-2023-proceedings-software-citation) that worked 5 hours ago and now with no changes to the GitHub Actions workflow

```yaml
...

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

...

jobs:

...

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v3

...

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
```

`actions/upload-pages-artifact@v2` is succeeding (as expected)

```
With the provided path, there will be 1 file uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "github-pages" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 91038 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!

The raw size of all the files that were specified for upload is 102400 bytes
The size of all the files that were uploaded is 91038 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

Artifact github-pages has been successfully uploaded!
```

but then `actions/deploy-pages@v2` is failing with

```
Artifact exchange URL: https://pipelinesghubeus7.actions.githubusercontent.com/MRRFg7wazEjuUfP6wl9C860DSXHdL0R9UvtunX1JdvJ7cAPJoH/_apis/pipelines/workflows/6275317421/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelinesghubeus7.actions.githubusercontent.com/MRRFg7wazEjuUfP6wl9C860DSXHdL0R9UvtunX1JdvJ7cAPJoH/_apis/pipelines/1/runs/6/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "342dcb9c508e0f873196d0c332e98c7ac6852dfd",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Invalid artifact url
    at /home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:126:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:80:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version 342dcb9c508e0f873196d0c332e98c7ac6852dfd. Responded with: Invalid artifact url
```

https://www.githubstatus.com/ is also not currently showing any degraded performance.

Does anyone know what broke?

**Comment by jameschensmith** [comment]
I'm experiencing this issue as well. Not sure if this helps, but I noticed the base URL has changed:
- Successful pipeline: `https://pipelines.actions.githubusercontent.com`
- Failed pipeline: `https://pipelinesghubeus7.actions.githubusercontent.com`

**Comment by GlobalMin** [comment]
Experiencing as well and linking to large thread where we have 20 or so confirmations and growing.

https://github.com/orgs/community/discussions/67961

**Comment by Bluefissure** [comment]
I think it is a server-side issue, I checked the log of previous successful runs and github was returning the `https://pipelines.actions.githubusercontent.com` as artifact raw url. Starting earlier today the returned url was changed to the mirror sites, which causes it to be invalid.

**Comment by viac92** [comment]
The last successful deployment of my website was 1 hour ago 16pm CEST, after that I tried few minutes later but every attempts failed.

**Comment by GlobalMin** [comment]
@JamesMGreene looks like you maintain this repo

**Comment by ghkdqhrbals** [comment]
There appears to be a permissions issue with the new request URL `https://pipelinesghebeus7.actions.githubusercontent.com`.

When I checked the URL above, it said `The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not Authorized`. From my point of view, `System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa` is not a common view. So, this access ID has been merged incorrectly.

**Comment by dgarcu** [comment]
I have experienced problems too. I have also commented on the mentioned thread.

**Comment by kstiehl** [comment]
We have the same issue here

**Comment by v8-j** [comment]
And me

**Comment by akoroliova** [comment]
Upvoting, hope this is fixed soon

**Comment by jonjoncardoso** [comment]
Same problem here!

**Comment by dahmani-karim** [comment]
Hi ! Same error in my workflow, invalid artifact url errors stop the publish action

**Comment by ChrisHammond** [comment]
+1

**Comment by mlettini** [comment]
Same

**Comment by Ew4n1011** [comment]
Upvoting, same error on my workflow, hopefully fixed soon

**Comment by pindoghd** [comment]
same error is it looking like a server problem?

**Comment by JamesMGreene** [comment]
I'll start investigating. Guessing an upstream change rolled out today. 😓

**Comment by Aripander088e2** [comment]
Okay so it is not just me lol

**Comment by pindoghd** [comment]
Thank you James, I did a little bit of digging around the GitHub community
forums and it seems to be quite a popular issue at the moment

**Comment by Aripander088e2** [comment]
Could it be that I was pushing tens of commits out in a short span using the pages

**Comment by NadyaNayme** [comment]
> Could it be that I was pushing tens of commits out in a short span using the pages

I started a new repo with a single commit for the purpose of deploying it through Pages and encountered this issue. As others have investigated - it looks like the new request URL broke things.

**Comment by matthewfeickert** [comment]
I think it is safe to say that this is already under investiagation by teams at GitHub (thanks for moving on this fast :pray:), so I think we can all hold tight and wait until things have been resolved.

**Comment by ChrisHammond** [comment]
> I think it is safe to say that this is already under investiagation by teams at GitHub (thanks for moving on this fast 🙏), so I think we can all hold tight and wait until things have been resolved.

until I see proof I don't believe! :D

**Comment by JamesMGreene** [comment]
**Update:** We have identified the issue internally. It is indeed related to an upstream rollout. We'll get the Pages deployment creation endpoint patched ASAP today to handle the new URL patterns. 👍🏻  I'll let you all know when it has shipped but it will probably be a few hours.

**Comment by ChrisHammond** [comment]
> **Update:** We have identified the issue internally. It is indeed related to an upstream rollout. We'll get the Pages deployment creation endpoint patched ASAP today to handle the new URL patterns. 👍🏻 I'll let you all know when it has shipped but it will probably be a few hours.

I believe!

**Comment by T313C0mun1s7** [comment]
It would be a good idea to update the status page. The first troubleshooting step says to check that thing, and to all appearances everything is good. So you have hundreds if not thousands of users assuming this is an issue on their end.

**Comment by ahsanjb** [comment]
:(

**Comment by v8-j** [comment]
> @JamesMGreene It would be a good idea to update the status page. The first troubleshooting step says to check that thing, and to all appearances everything is good. So you have hundreds if not thousands of users assuming this is an issue on their end.

My keyboard is banana shaped now

**Comment by JamesMGreene** [comment]
@T313C0mun1s7 Very true. I was trying to establish the actual impact first, which should _not_ be affecting all users as I currently understand it. I've set Pages to status yellow 🟡 now. 👍🏻

**Comment by jellyfishstar** [comment]
I want to cry

**Comment by T313C0mun1s7** [comment]
@JamesMGreene I literally have a README.md and an extremely simple 10 line index.html, and it is just in the root of my main branch.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Mastodon Verification for T313C0mun1s7</title>
  </head>
  <body>
    <a rel="me" href="https://fosstodon.org/@T313C0mun1s7">https://fosstodon.org/@T313C0mun1s7</a>
  </body>
</html>
```
So if it is affecting me, I assumed it affected everyone.

**Comment by MdNData** [comment]
Same issue hopefully the github team is taking care of it! :)

**Comment by steliancardos** [comment]
It-s not working for me either, i only have a index file and it just throws the following errors:
Error: Creating Pages deployment failed
Error: HttpError: Invalid artifact url

**Comment by T313C0mun1s7** [comment]
Status page just went back to green - It is fixed I presume?

**Comment by v8-j** [comment]
It is fixed :)

**Comment by T313C0mun1s7** [comment]
Verified, working for me as well.

**Comment by Ew4n1011** [comment]
Yeah, works for me too.

**Comment by ericleirosario** [comment]
Problema corrigido !

**Comment by cldwalker** [comment]
Works for me too. Thanks @JamesMGreene!

**Comment by JamesMGreene** [comment]
> So if it is affecting me, I assumed it affected everyone.

@T313C0mun1s7 Unfortunately, it has nothing to due with a site's complexity, just which artifact servers it ended up using.

Yes, we're back to status green 🟢: https://www.githubstatus.com/incidents/4ypqyv8zbrck

_Nearly_ everyone should be able to successfully create Pages deployments as before, though the last very small slice of users should be fixed in the next hour or so when my internal pull request gets deployed to fully cover the situation.

Thanks to all for your reporting and patience. This one admittedly caught us by surprise, so we'll be sure to improve our monitoring configurations. ❤️

**Comment by jpzwolak** [comment]
works for me now!

**Comment by suvadityamuk** [comment]
I'm getting this issue once again. 

```

deployCreating Pages deployment failed
--
deployHttpError: Validation Failed     at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:124:1     at processTicksAndRejections (node:internal/process/task_queues:95:5)     at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:125:1)     at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:74:1)     at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)Show less
deployError: Failed to create deployment (status: 422) with build version 5fd21e81323b2ea73a8a0991abc9341d84e190ed. Request ID 5501:B384C:43E431:8926EC:67B54BCC

[deploy](https://github.com/suvadityamuk/hugo-website/actions/runs/13404628985/job/37442242923#step:2:20)
Creating Pages deployment failed
[deploy](https://github.com/suvadityamuk/hugo-website/actions/runs/13404628985/job/37442242923#step:2:21)
HttpError: Validation Failed
    at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:125:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:74:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
[deploy](https://github.com/suvadityamuk/hugo-website/actions/runs/13404628985/job/37442242923#step:2:27)
Error: Failed to create deployment (status: 422) with build version 5fd21e81323b2ea73a8a0991abc9341d84e190ed. Request ID 5501:B384C:43E431:8926EC:67B54BCC
```

Upon going to the deployment artifact exchange URL (which shows to be https://pipelinesghubeus8.actions.githubusercontent.com/FBpS4qNkMzmhGL7Oydyfd3DBTIjLLZcBpP0qEjSYDMghnv3RvW/_apis/pipelines/workflows/13404664868/artifacts?api-version=6.0-preview), it keeps showing

```
{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

My workflow is attached below:
```
name: Deploy Wowchemy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.119.0'

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build website
  build:
    if: github.repository_owner != 'wowchemy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch history for Hugo's .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deploy website to GitHub Pages hosting
  deploy:
    if: github.repository_owner != 'wowchemy'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

Please let me know if there are any available fixes for this. Thank you!
