### ISSUE TITLE
Fails with Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable

### ISSUE THREAD

**Issue by staff0rd** [actions/deploy-pages#28]
The following workflow fails for both `actions/deploy-pages@v1-beta` and `actions/deploy-pages@v1`. This workflow reflects the format noted in #9.

```yaml
name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Archive
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1-beta
```

Result
```
2022-03-31T02:20:44.9923161Z ##[group]Run actions/deploy-pages@v1-beta
2022-03-31T02:20:44.9923517Z with:
2022-03-31T02:20:44.9923999Z   token: ***
2022-03-31T02:20:44.9924270Z   timeout: 600000
2022-03-31T02:20:44.9924538Z   error_count: 10
2022-03-31T02:20:44.9924827Z   reporting_interval: 1000
2022-03-31T02:20:44.9925097Z ##[endgroup]
2022-03-31T02:20:45.0687762Z ##[error]Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

**Comment by misirlou-tg** [comment]
I believe you still need the `permissions` block from issue #9, you only need to add it to the `deploy` job.

I followed the format from that issue, the only difference was I used `deploy-pages@v1` and was able to get it working.

**Comment by staff0rd** [comment]
Thanks @misirlou-tg you are right, i was missing

```
permissions:
  contents: read
  pages: write
  id-token: write
```
