### ISSUE TITLE
Invalid deployment branch and no branch protection rules set in the environment

### ISSUE THREAD

**Issue by Jeffwan** [actions/deploy-pages#33]
https://github.com/ray-project/kuberay/runs/6090920605?check_suite_focus=true

We have Ci jobs using mkdocs to deploy github pages. However, seems release plugin doesn't work well. We do see following error

```
"Invalid deployment branch and no branch protection rules set in the environment. Deployments are only allowed from gh-pages
```
I am not sure how we can fix this problem. Any clues?

```
Run actions/deploy-pages@v1
Actor: Jeffwan
Action ID: 2149399226
Artifact URL: https://pipelines.actions.githubusercontent.com/tKRfNbyaGNzId1XJxdkv7FJQ4Qp5iGkvmd6XKRWbtSm3T51lc7/_apis/pipelines/workflows/2149399226/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":24295065,"size":[8](https://github.com/ray-project/kuberay/runs/6090920605?check_suite_focus=true#step:2:8)2[9](https://github.com/ray-project/kuberay/runs/6090920605?check_suite_focus=true#step:2:9)440,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/tKRfNbyaGNzId1XJxdkv7FJQ4Qp5iGkvmd6XKRWbtSm3T51lc7/_apis/resources/Containers/24295065","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/tKRfNbyaGNzId1XJxdkv7FJQ4Qp5iGkvmd6XKRWbtSm3T51lc7/_apis/pipelines/1/runs/413/artifacts?artifactName=github-pages","expiresOn":"2022-07-19T07:42:[11](https://github.com/ray-project/kuberay/runs/6090920605?check_suite_focus=true#step:2:11).4562135Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/tKRfNbyaGNzId1XJxdkv7FJQ4Qp5iGkvmd6XKRWbtSm3T51lc7/_apis/pipelines/1/runs/413/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "c22f2ae76759e95bb3284ba5c2af0c359fec9[14](https://github.com/ray-project/kuberay/runs/6090920605?check_suite_focus=true#step:2:14)0",
	"oidc_token": "***"
}
Failed to create deployment for c22f2ae76759e95bb3284ba5c2af0c359fec9140.
{"message":"Invalid deployment branch and no branch protection rules set in the environment. Deployments are only allowed from gh-pages","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 400
Error: Error: Request failed with status code 400
```

```
name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
```

![image](https://user-images.githubusercontent.com/4739316/164180396-bba8d6a4-3980-47f7-ab9d-3a0501eff636.png)
