### ISSUE TITLE
Problem in page deployment with vuejs vite to github page

### ISSUE THREAD

**Issue by daironpf** [actions/deploy-pages#342]
Hello, I am deploying my page in vuejs vite(is the frontend of open source project) to github page with github action but the artifact is giving me an error, could someone help me with this problem.
Greetings

I attach the photo of my error and the link to my github action.
![error](https://github.com/actions/deploy-pages/assets/45364687/a09978bb-fcbe-4345-a5de-361edd48dd92)

[here the link to the action file](https://github.com/daironpf/SocialSeed/blob/main/.github/workflows/jekyll-gh-pages.yml)

**Comment by daironpf** [comment]
i make some changes in the code and now the error is this:
![error completo](https://github.com/actions/deploy-pages/assets/45364687/e0ddffd9-59ff-4ed4-a6ff-1944477c5aae)

**Comment by daironpf** [comment]
This is the code of my action
```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci        
      - name: Build      
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: /dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source: dist
```

**Comment by yoannchaudet** [comment]
Try changing the path from `/dist` to `./dist`. Removing the slash altogether could work too.

**Comment by daironpf** [comment]
> Try changing the path from `/dist` to `./dist`. Removing the slash altogether could work too.

1. change:
- name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
Result: Error.
throw this wairning at the same time of error: No files were found with the provided path: ./dist. No artifacts will be uploaded.

2. change:
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
Result:                     
          
![second error](https://github.com/actions/deploy-pages/assets/45364687/2ad3d6b2-3f9c-4d98-a80f-a33e5c3be1e7)

**Comment by yoannchaudet** [comment]
oh never mind did not see:

```
        working-directory: 'frontend'
```

Your artifacts' location is `./frontend/dist`.

**Comment by daironpf** [comment]
> oh never mind did not see:
> 
> ```
>         working-directory: 'frontend'
> ```
> 
> Your artifacts' location is `./frontend/dist`.

This is my new code and have the same error:
```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci        
      - name: Build      
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./frontend/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source: dist
```
[Here is the link to the .yml file](https://github.com/daironpf/SocialSeed/blob/main/.github/workflows/jekyll-gh-pages.yml)
