### ISSUE TITLE
Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable

### ISSUE THREAD

**Issue by AceKiron** [actions/deploy-pages#37]
```
Run actions/deploy-pages@main
  with:
    token: ***
    emit_telemetry: false
    timeout: 600000
    error_count: 10
    reporting_interval: [5](https://github.com/AceKiron/portfolio/runs/6745490016?check_suite_focus=true#step:7:5)000
Error: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

That's all it says, running this action using
```
- name: Deploy artifact
  uses: actions/deploy-pages@main
  with:
    token: ${{ github.token }}
```

Repository for example: https://github.com/AceKiron/portfolio
