### ISSUE TITLE
Pages successfully deployed but the opening the link presents a 404

### ISSUE THREAD

**Issue by tking16** [actions/deploy-pages#373]
Apologies I'm not too well versed with Github pages so may have made some obvious errors. I'm trying to push a html report from an Appium test run onto our orgs private pages repo. The folder I'm trying to upload looks as follows (it's a .tar):
![Screenshot 2024-09-19 at 12 30 40](https://github.com/user-attachments/assets/11992f3e-cbac-4e14-8601-53c0c4caab40)

As mentioned though I'm just getting 404 not found when trying to access the link. I'll post just the reporting job below:
<details>
<summary> report job YAML </summary>
```
  reporting:
    if: always()
    needs: test
    name: Put report onto GH pages
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: mobile-test-reports
      url: ${{ steps.deployment.outputs.page_url }}ios-report
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5


      - name: Display URL to report
        run: echo '## [Test Report] ('${{ steps.deployment.outputs.page_url }}')' >> $GITHUB_STEP_SUMMARY
```
</details>

Output from job status
```
Run actions/deploy-pages@v4.0.5
Fetching artifact metadata for "github-pages" in this workflow run
Found 1 artifact(s***
Creating Pages deployment with payload:
{
	"artifact_id": 1952676[30](https://github.com/global-digital-dev/guacamole/actions/runs/10939969440/job/30371396627#step:2:31)6,
	"pages_build_version": "843e4097e3d59d74c555e6a753713046e11743b7",
	"oidc_token": "***"
}
Created deployment for 843e4097e3d59d74c555e6a753713046e11743b7, ID: 843e4097e3d59d74c555e6a753713046e11743b7
Getting Pages deployment status...
Reported success!
```

Thanks in advance for the help and let me know if you need more info
