### ISSUE TITLE
Support specify folder to deploy

### ISSUE THREAD

**Issue by guoyunhe** [actions/deploy-pages#385]
Most modern web builders output result files at `dist`, `build` or `output` folders, not root folder. Can this action support configuration of root path?

```yml
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          root: ./dist
```
