### ISSUE TITLE
Missing download info for actions/deploy-page@v4

### ISSUE THREAD

**Issue by rerdavies** [actions/deploy-pages#394]
My website deployment action has broken, presumably due to version dependencies in the various page actions.  It has been rewritten to use the two-job setup in the sample file on the deploy_pages README.md, and version numbers have been bumped from @1 to those on the current README.md page. (It original ran as a single deploy job using @v1 actions). I have followed the examples on the deploy-page README.md file as carefully as I can while rewriting the .yml file, with minor modifications preserved.

The deploy  job fails with the following error:

```
[deploy](https://github.com/rerdavies/lv2cairo/actions/runs/14210010845/job/39815356836#step:1:24)
Missing download info for actions/deploy-page@v4
```

The pages get built properly. The artifact gets properly created with a name of github-pages.zip.  The zip file contains a file called `artifact.tar`  which contains static pages starting at the root of the website. (Should it be in a `_site` directory? The docs are ambiguous).

The pages are static pages built by vite, into the `website/dist/` directory.

lv2cairo/.github/workflows/website-build.yml
```
# Workflow for deploying static content to GitHub Pages
name: Deploy github.io website

on:
  # Runs on pushes to the webites/ directory in the default branch
  push:
    paths:
      - 'website/**'
      - '.github/workflows/website-build.yml'
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true
 
jobs:
  # Two job deployment. Build first; deploy afterward.
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        working-directory: 'website' 
        run: |
          ls -la
          npm install
      - name: Build
        working-directory: 'website' 
        run: |
          npm run build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload built dist directory
          path: './website/dist'
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
       pages: write
       id-token: write
         
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-page@v4
```

The full output from the deploy job is:
```
Current runner version: '2.323.0'
Operating System
Runner Image
Runner Image Provisioner
> GITHUB_TOKEN Permissions
> Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Missing download info for actions/deploy-page@v4
```

upload-artifact@v3 produces the following output:

```
with:
    name: github-pages
    path: /home/runner/work/_temp/artifact.tar
    retention-days: 1
    if-no-files-found: error
    compression-level: 6
    overwrite: false
    include-hidden-files: false
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Uploaded bytes 209129
Finished uploading artifact content to blob storage!
SHA256 digest of uploaded artifact zip is 3abae4b588946a1526255990dd938709dee2e135a2ac0f4445245379e601adbc
Finalizing artifact upload
Artifact github-pages.zip successfully finalized. Artifact ID 28642[54](https://github.com/rerdavies/lv2cairo/actions/runs/14210563688/job/39816849808#step:6:57)052
Artifact github-pages has been successfully uploaded! Final size is 209129 bytes. Artifact ID is 2864254052
Artifact download URL: https://github.com/rerdavies/lv2cairo/actions/runs/14210[56](https://github.com/rerdavies/lv2cairo/actions/runs/14210563688/job/39816849808#step:6:59)3688/artifacts/2864254052
```
