### ISSUE TITLE
Uploaded files' modification dates are overriden

### ISSUE THREAD

**Issue by denis-migdal** [actions/deploy-pages#396]
Hi,

I am currently using `document.lastModified` in my github pages to print the page last modification date.

For that, I use the [git-restore-mtime-action](https://github.com/chetan/git-restore-mtime-action) github action in order to properly set the files last modification date.

I looked at the artifact generated by `actions/upload-pages-artifact@v3` and the date seems correct.

However, when I check the `document.lastModified` of my github pages, the last modification date is set to the date of the last github action execution.

**Comment by denis-migdal** [comment]
Well that's kind of a standard workflow :
```yml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './dist/prod/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

When I download the artefact, the modification date are correct.
But when I go the the gitpages, `document.lastModified` is set to the date for the action execution.
