### ISSUE TITLE
Deplay-pages action failed even i have clean up the artifacts as suggested

### ISSUE THREAD

**Issue by ZhuBicen** [actions/deploy-pages#400]
The error message: Artifact could not be deployed. Please ensure the content does not contain any hard links, symlinks and total size is less than 10GB.

As can see from My workflow, i tried remove big files, soft links, hardlinks, the whole artifacts about 18MB, but it still failed, can the deploy-pages actions provide more useful information?

```
# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.122.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Log Artifact Details
        run: |
          du -sh public/
          find public -type l -exec ls -l {} \;
          find public -type f -links +1 -exec ls -l {} \;
          cd public && ls -ahlv && cd ..
          cd public && tree && cd ..

      - name: Clean Up Artifact Directory
        run: |
          rm -rf public/unnecessary-folder
          find public -type l -delete # Ensure symlinks are deleted
          find public -type f -links +1 -delete # Ensure hard links are deleted
          find public -size +100M -delete # Deletes files larger than 100MB
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public # Path to the folder containing the site files generated by Hugo            
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```
A link to your workflow run: 
https://github.com/ZhuBicen/zhubicen.github.io/actions/runs/15548674193/job/43774947521 (useful for maintainers).
