### ISSUE TITLE
Can we support deploying from tags?

### ISSUE THREAD

**Issue by dancrumb** [actions/deploy-pages#76]
I have the following workflow:

```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Setup yarn
        run: yarn
      - name: Build docs
        run: yarn run docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

I created a tag and the job failed with no logs and the following on the UI:

```
Branch "v2.0.2" is not allowed to deploy to github-pages due to environment protection rules.
```

and 

```
The deployment was rejected or didn't satisfy other protection rules.
```

It would be great to get support for deploying docs on a tag
